### ISSUE TITLE
mserver start - bez argumentu

### ISSUE THREAD

**Issue by moora** [jaburjak/pohodactl#1]
nastartuje všechny mServery, které jsou na danné instanci definované, kromě těch, které již běží

**Comment by moora** [comment]
ještě by stálo za zvážení umět spustit msever tak, aby se uživatel mohl odhlásit a process mohl dále běžet - mohu dodat návod

**Comment by jaburjak** [comment]
Spouštění všech mServerů implementováno v ba8bed5.

Pro spuštění na pozadí může uživatel spustit pohodactl vhodnými nástroji systému Windows (např. Plánovačem úloh).
