### ISSUE TITLE
nový příkaz - mserver test jmeno_mserveru

### ISSUE THREAD

**Issue by moora** [jaburjak/pohodactl#3]
otestuje zda mserver konkrétního jména na instanci komunikuje - ne pouze status zda běží. Máme praxi, že běžící mserver nekomunikuje

**Comment by jaburjak** [comment]
V 41210ae implementován nový příkaz: `pohodactl.ps1 mserver health`, který odešle autentifikovaný HTTP požadavek na mServer a tím ověří, že opravdu odpovídá. Do `pohodactl.conf` je nutné doplnit proměnné `PHUSER` a `PHPASSWORD` s přihlašovacími údaji uživatele v Pohodě.
